# Generated by Django 4.2.28 on 2026-02-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_link',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(default='No requirements specified'),
        ),
    ]
