# Generated by Django 4.2.28 on 2026-02-27 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('qualification', models.CharField(blank=True, help_text='e.g. B.Tech Computer Science, MBA', max_length=200)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('graduation_year', models.CharField(blank=True, max_length=4)),
                ('preferred_job_type', models.CharField(blank=True, choices=[('fulltime', 'Full Time'), ('intern', 'Internship'), ('fresher', 'Fresher'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=20)),
                ('preferred_skills', models.CharField(blank=True, help_text='e.g. Python, React, Django', max_length=300)),
                ('preferred_location', models.CharField(blank=True, max_length=100)),
                ('expected_salary', models.CharField(blank=True, help_text='e.g. 8-12 LPA', max_length=50)),
                ('last_company', models.CharField(blank=True, max_length=200)),
                ('last_job_title', models.CharField(blank=True, max_length=200)),
                ('last_job_from', models.CharField(blank=True, help_text='e.g. Jan 2022', max_length=20)),
                ('last_job_to', models.CharField(blank=True, help_text='e.g. Dec 2023 or Present', max_length=20)),
                ('experience_years', models.CharField(blank=True, help_text='e.g. 2.5', max_length=10)),
                ('last_job_desc', models.TextField(blank=True, help_text='Brief description of responsibilities')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
